AWSTemplateFormatVersion: '2010-09-09'
Description: A simple CloudFormation template to create an IAM user, Roles, Auto Scaling Groups and S3 bucket access C.

Resources:
  NpdIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: npd-dev01

  NpdS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: npd-dev-bucket01

  NpdIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: npd-ec2-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - "arn:aws:s3:::npd-dev-bucket01"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - "arn:aws:s3:::npd-dev-bucket01/*"




